name: Documentation deployment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    rons-on: ubuntu-latest
    steps:
      - name: Code Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build 🔧
        run: |
          yarn install --frozen-lockfile
          yarn run generate-docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build